# Generated by Django 4.2.2 on 2023-06-13 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0002_academicprogramme_academictimeline_academicyear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch_year',
        ),
        migrations.DeleteModel(
            name='StudentBatch',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pm_base.level'),
        ),
    ]
