# Generated by Django 4.2.2 on 2023-06-14 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0005_coursefee_studentgrade_delete_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('with_penality', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('First Installment Complete', 'First Installment Complete'), ('stalled', 'Stalled')], default='Incomplete', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_base.student')),
            ],
        ),
    ]
