# Generated by Django 4.2.2 on 2023-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0006_paymentinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
