# Generated by Django 4.2.2 on 2023-06-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0008_student_entry_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
