# Generated by Django 4.2.2 on 2023-06-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0011_teacher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ManyToManyField(related_name='courses', to='pm_base.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pm_base.student')),
            ],
        ),
    ]
