# Generated by Django 4.2.2 on 2023-06-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0012_courseeligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseeligibility',
            name='academic_programme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pm_base.academicprogramme'),
            preserve_default=False,
        ),
    ]
