# Generated by Django 4.2.2 on 2023-06-14 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_base', '0013_courseeligibility_academic_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseeligibility',
            name='academic_programme',
        ),
        migrations.AddField(
            model_name='courseeligibility',
            name='academic_time_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pm_base.academictimeline'),
            preserve_default=False,
        ),
    ]
